import type { Metadata } from "next";
import { ReactNode } from "react";
import { ClientWrapper } from "@/components/ClientWrapper";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: ReactNode;
}

export default function RootLayout({
  children,
}: Readonly<LayoutProps>) {
  return (
    <html lang="en">
      <body className="antialiased bg-black text-white" style={{ fontSize: "16px" }}>
        <ClientWrapper>
          <div className="flex flex-col min-h-screen">
            <Header />
            <main className="flex-1 flex flex-col justify-between p-4">
              {children}
            </main>
            <Footer />
          </div>
        </ClientWrapper>
      </body>
    </html>
  );
}